version: '3.7'
services:

  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: recipe_db
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db:delegated 
      - ./src/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  webpack:
    image: node:16.14
    volumes:
      - ./:/app:delegated
    working_dir: /app
    command: npm run dev
    ports:
      - 8080:8080

  node:
    depends_on:
      - mongodb
    image: node:16.14
    volumes:
      - ./:/app:delegated
    working_dir: /app
    command: npm run dev-server
    ports:
      - 8081:8081
      - 9229:9229
    environment:
      DB_USER: chef
      DB_PASSWORD: pizza
      DB_HOST: host.docker.internal
      DB_PORT: 27017
      DB_NAME: recipe_db
